
server:
  port:
    9003

spring:
  application:
    name:
      back-dashboard
      
  zipkin:
    base-url: http://localhost:9412

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka # 서버에 따라 다르게 설정 (기본갑)
      defaultZone: http://ec2-43-203-124-16.ap-northeast-2.compute.amazonaws.com:8761/eureka

logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG
          
API_GATEWAY_URL: http://ec2-43-203-124-16.ap-northeast-2.compute.amazonaws.com:9002 # 기본값 http://localhost:9002
